name: Build FFmpeg with x264 (MSVC, dynamic)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install -y ninja cmake 7zip

    - name: Clone vcpkg and bootstrap
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    - name: Install x264 with vcpkg
      run: |
        cd vcpkg
        .\vcpkg install x264:x64-windows
      # 设置环境变量供后续步骤使用
      env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    - name: Clone FFmpeg
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        git checkout n4.4.6

    - name: Configure FFmpeg with MSVC environment
      shell: cmd
      run: |
        REM 加载 Visual Studio MSVC 编译环境 (路径根据你使用的 VS 版本调整)
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

        REM 设置vcpkg路径变量，改成你的路径
        set VCPKG_PATH=%GITHUB_WORKSPACE%\vcpkg
        set PATH=%VCPKG_PATH%\installed\x64-windows\bin;%PATH%
        set INCLUDE=%VCPKG_PATH%\installed\x64-windows\include;%INCLUDE%
        set LIB=%VCPKG_PATH%\installed\x64-windows\lib;%LIB%

        REM 在加载MSVC环境的cmd中调用bash的configure，确保cl.exe可用
        bash -c "cd ffmpeg && ./configure --toolchain=msvc \
          --prefix=$GITHUB_WORKSPACE/ffmpeg-install \
          --target-os=win64 \
          --arch=x86_64 \
          --enable-gpl \
          --enable-libx264 \
          --disable-everything \
          --enable-encoder=libx264 \
          --enable-decoder=h264 \
          --enable-muxer=mp4 \
          --enable-demuxer=h264 \
          --enable-protocol=file \
          --enable-ffmpeg \
          --disable-ffplay \
          --disable-ffprobe \
          --enable-shared \
          --disable-static"

    - name: Build FFmpeg with MSVC
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
        cd ffmpeg
        nmake
        nmake install

    - name: Package output
      run: |
        7z a ffmpeg-windows-msvc-x64.zip .\ffmpeg-install\*

    - name: Generate unique tag
      shell: bash
      id: tag
      run: |
        base="v$(date +'%Y.%m.%d')"
        n=1
        while git ls-remote --exit-code --tags origin "$base.$(printf '%03d' $n)" &> /dev/null; do
          n=$((n + 1))
        done
        tag="$base.$(printf '%03d' $n)"
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Create Git Tag
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.tag.outputs.tag }}
        git push origin ${{ steps.tag.outputs.tag }}

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: FFmpeg MSVC Release ${{ steps.tag.outputs.tag }}
        files: ffmpeg-windows-msvc-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
