name: Build FFmpeg with x264

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到最新版本

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-x264
          mingw-w64-x86_64-nasm

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-x264-binaries
        path: ffmpeg-x264.zip

    - name: Configure environment
      shell: msys2 {0}
      run: |
        echo "PATH=$PATH:/mingw64/bin" >> $GITHUB_ENV

    - name: Download FFmpeg source
      shell: bash
      run: |
        curl -L https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 -o ffmpeg.tar.bz2
        tar -xjf ffmpeg.tar.bz2

    - name: Configure FFmpeg
      shell: msys2 {0}
      run: |
        cd ffmpeg
        ./configure \
          --prefix=/mingw64/ffmpeg-build \
          --arch=x86_64 \
          --target-os=mingw32 \
          --enable-gpl \
          --enable-libx264 \
          --enable-static \
          --disable-shared \
          --disable-programs \
          --disable-doc \
          --extra-cflags="-I/mingw64/include" \
          --extra-ldflags="-L/mingw64/lib"

    - name: Build and install
      shell: msys2 {0}
      run: |
        cd ffmpeg
        make -j$(nproc)
        make install

    - name: Package binaries
      shell: cmd
      run: |
        7z a -tzip ffmpeg-x264.zip "%MSYS2_PATH%\mingw64\ffmpeg-build\bin\*"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-x264-binaries
        path: ffmpeg-x264.zip

    # 可选：自动创建 Release 并上传
    # - name: Create Release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: ffmpeg-x264.zip
    #     draft: false
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
