name: Build FFmpeg with x264 (Windows, dynamic)

on:
  workflow_dispatch:

permissions:
  contents: write  # 必须授权写权限才能发布 Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          nasm
          yasm
          make
          pkg-config
          mingw-w64-x86_64-x264

    - name: Clone FFmpeg
      shell: msys2 {0}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        git checkout n6.1.1

    - name: Configure FFmpeg (shared, x264 only)
      shell: msys2 {0}
      run: |
        cd ffmpeg
        ./configure --prefix=/usr/local \
                    --target-os=mingw32 \
                    --arch=x86_64 \
                    --enable-gpl \
                    --enable-libx264 \
                    --disable-vaapi \
                    --disable-everything \
                    --enable-encoder=libx264 \
                    --enable-decoder=h264 \
                    --enable-muxer=mp4 \
                    --enable-demuxer=h264 \
                    --enable-protocol=file \
                    --enable-ffmpeg \
                    --disable-ffplay \
                    --disable-ffprobe \
                    --enable-shared \
                    --disable-static \
                    --disable-doc \
                    --extra-cflags="-D_WIN32_WINNT=0x0601" \
                    --extra-ldflags="-static-libgcc"

    - name: Build and install
      shell: msys2 {0}
      run: |
        cd ffmpeg
        make -j$(nproc)
        make install

    - name: Prepare output
      shell: msys2 {0}
      run: |
        mkdir -p ffmpeg-package/bin
        mkdir -p ffmpeg-package/include
        mkdir -p ffmpeg-package/lib

        # FFmpeg 输出
        cp -r /usr/local/bin/* ffmpeg-package/bin/
        cp -r /usr/local/include/* ffmpeg-package/include/
        cp -r /usr/local/lib/* ffmpeg-package/lib/

        # x264 动态库与头文件（来自 MSYS2 自带的 x264）
        cp /mingw64/bin/libx264-*.dll ffmpeg-package/bin/
        cp -r /mingw64/include/x264.h ffmpeg-package/include/
        cp -r /mingw64/lib/libx264.dll.a ffmpeg-package/lib/

        # FFmpeg 预设文件（可选）
        if [ -d /usr/local/share/ffmpeg ]; then
          mkdir -p ffmpeg-package/presets
          cp -r /usr/local/share/ffmpeg/* ffmpeg-package/presets/
        fi

    - name: Compress to zip
      shell: bash
      run: |
        7z a ffmpeg-windows-x64-x264.zip ./ffmpeg-package/*

    - name: Generate unique tag
      id: tag
      shell: bash
      run: |
        base="v$(date +'%Y.%m.%d')"
        n=1
        while git ls-remote --exit-code --tags origin "$base.$(printf '%03d' $n)" &> /dev/null; do
          n=$((n + 1))
        done
        tag="$base.$(printf '%03d' $n)"
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Create Git Tag
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.tag.outputs.tag }}
        git push origin ${{ steps.tag.outputs.tag }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: FFmpeg Release ${{ steps.tag.outputs.tag }}
        files: ffmpeg-windows-x64-x264.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
