name: Build FFmpeg with x264 (Windows, dynamic)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          nasm
          yasm
          make
          pkg-config
          mingw-w64-x86_64-x264
          zstd

    - name: Clone FFmpeg
      shell: msys2 {0}
      run: |
        git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        git checkout n6.1

    - name: Apply compatibility patch
      shell: msys2 {0}
      run: |
        cd ffmpeg
        cat > compat.patch << 'EOF'
        diff --git a/configure b/configure
        index 7f5c5d3..a1b3e5e 100755
        --- a/configure
        +++ b/configure
        @@ -5794,6 +5794,7 @@ case $target_os in
             ;;
         mingw32*)
             enabled shared && ! enabled small && test_cmd $windres --version && enable gnu_windres
        +    add_cflags -D_WIN32_WINNT=0x0601
             ;;
         linux)
             enable section_data_rel_ro
        EOF
        git apply compat.patch

    - name: Configure FFmpeg
      shell: msys2 {0}
      run: |
        cd ffmpeg
        ./configure \
          --prefix=/mingw64 \
          --arch=x86_64 \
          --target-os=mingw32 \
          --cross-prefix=x86_64-w64-mingw32- \
          --enable-gpl \
          --enable-libx264 \
          --disable-everything \
          --enable-encoder=libx264 \
          --enable-decoder=h264 \
          --enable-muxer=mp4 \
          --enable-demuxer=h264 \
          --enable-protocol=file \
          --enable-ffmpeg \
          --disable-ffplay \
          --disable-ffprobe \
          --enable-shared \
          --disable-static \
          --disable-doc \
          --extra-cflags="-static-libgcc" \
          --extra-ldflags="-static-libgcc"

    - name: Build and install
      shell: msys2 {0}
      run: |
        cd ffmpeg
        make -j$(nproc)
        make install

    - name: Prepare runtime libraries
      shell: msys2 {0}
      run: |
        mkdir -p ffmpeg-dist
        # 主程序文件
        cp /mingw64/bin/ffmpeg.exe ffmpeg-dist/
        
        # 必需DLL（排除有兼容性问题的版本）
        cp /mingw64/bin/avcodec-58.dll ffmpeg-dist/
        cp /mingw64/bin/avformat-58.dll ffmpeg-dist/
        cp /mingw64/bin/avutil-56.dll ffmpeg-dist/
        cp /mingw64/bin/swresample-3.dll ffmpeg-dist/
        cp /mingw64/bin/swscale-5.dll ffmpeg-dist/
        cp /mingw64/bin/libx264-*.dll ffmpeg-dist/
        
        # 下载旧版运行时库（GCC 11.3.0）
        curl -L -o old_runtime.tar.zst https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-11.3.0-3-any.pkg.tar.zst
        tar -I zstd -xf old_runtime.tar.zst -C ffmpeg-dist usr/bin/libgcc_s_seh-1.dll usr/bin/libwinpthread-1.dll
        mv ffmpeg-dist/usr/bin/*.dll ffmpeg-dist/
        rm -rf ffmpeg-dist/usr old_runtime.tar.zst

    - name: Verify dependencies
      shell: cmd
      run: |
        cd ffmpeg-dist
        dumpbin /dependents ffmpeg.exe > deps.txt
        findstr "clock_gettime64" deps.txt && exit 1 || exit 0

    - name: Compress artifacts
      shell: bash
      run: |
        7z a -tzip ffmpeg-win64-x264-dynamic.zip ./ffmpeg-dist/*

    - name: Generate version tag
      id: version
      shell: bash
      run: |
        version=$(date -u +'%Y.%m.%d')
        build_num=1
        while git ls-remote --exit-code --tags origin "v$version.$build_num" &>/dev/null; do
          ((build_num++))
        done
        echo "tag=v$version.$build_num" >> $GITHUB_OUTPUT
        echo "name=FFmpeg Windows x64 (x264) $version.$build_num" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: ${{ steps.version.outputs.name }}
        files: ffmpeg-win64-x264-dynamic.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
