name: Build FFmpeg with x264 (Windows, dynamic)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          nasm
          yasm
          make
          pkg-config
          mingw-w64-x86_64-x264

    - name: Clone FFmpeg
      shell: msys2 {0}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        git checkout n6.1  # 可根据需要更换版本

    - name: Configure FFmpeg (shared build, x264 only)
      shell: msys2 {0}
      run: |
        cd ffmpeg
        ./configure --prefix=/usr/local \
                    --target-os=mingw32 \
                    --arch=x86_64 \
                    --enable-gpl \
                    --enable-libx264 \
                    --disable-every
