name: Build FFmpeg with x264 (Windows, dynamic)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # 用于创建 tag 和 release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          nasm
          yasm
          make
          pkg-config
          mingw-w64-x86_64-x264

    - name: Clone FFmpeg
      shell: msys2 {0}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git
        cd ffmpeg
        git checkout n6.1

    - name: Configure FFmpeg (shared build, x264 only)
      shell: msys2 {0}
      run: |
        cd ffmpeg
        ./configure --prefix=/usr/local \
                    --target-os=mingw32 \
                    --arch=x86_64 \
                    --enable-gpl \
                    --enable-libx264 \
                    --disable-everything \
                    --enable-encoder=libx264 \
                    --enable-decoder=h264 \
                    --enable-muxer=mp4 \
                    --enable-demuxer=h264 \
                    --enable-protocol=file \
                    --enable-ffmpeg \
                    --disable-ffplay \
                    --disable-ffprobe \
                    --enable-shared \
                    --disable-static

    - name: Build and install FFmpeg
      shell: msys2 {0}
      run: |
        cd ffmpeg
        make -j$(nproc)
        make install

    - name: Prepare full FFmpeg package
      shell: msys2 {0}
      run: |
        mkdir -p ffmpeg-package
        cp -r /usr/local/bin ffmpeg-package/
        cp -r /usr/local/include ffmpeg-package/
        cp -r /usr/local/lib ffmpeg-package/
        if [ -d /usr/local/share/ffmpeg ]; then
          cp -r /usr/local/share/ffmpeg ffmpeg-package/presets
        fi

    - name: Compress to zip
      shell: bash
      run: |
        7z a ffmpeg-windows-x64-x264.zip ./ffmpeg-package/*

    - name: Create tag name
      id: tag
      shell: bash
      run: |
        DATE_TAG="v$(date +'%Y.%m.%d').001"
        echo "tag=$DATE_TAG" >> $GITHUB_OUTPUT

    - name: Create Git Tag
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.tag.outputs.tag }}
        git push origin ${{ steps.tag.outputs.tag }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Release ${{ steps.tag.outputs.tag }}
        files: ffmpeg-windows-x64-x264.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
