name: Build FFmpeg DLL (x264, MSVC)

on:
  workflow_dispatch:

permissions:
  contents: write  # 必须授权写权限才能发布 Release

jobs:
  build:
    runs-on: windows-latest

    env:
      FFMPEG_VERSION: n6.1
      BUILD_DIR: ${{ github.workspace }}\ffmpeg-build
      INSTALL_DIR: ${{ github.workspace }}\ffmpeg-output

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install -y nasm
        git clone --depth=1 https://github.com/ShiftMediaProject/x264
        cd x264
        msbuild x264.sln /p:Configuration=Release /p:Platform=x64
        cd ..

    - name: Clone FFmpeg and FFVS Generator
      run: |
        git clone --depth=1 https://github.com/FFVS/FFVS-Project-Generator FFVS
        git clone --depth=1 https://github.com/FFmpeg/FFmpeg -b %FFMPEG_VERSION% ffmpeg

    - name: Generate FFmpeg DLL Project
      run: |
        cd FFVS
        .\GenerateFFmpegProject.bat ..\ffmpeg ..\x264 dll

    - name: Build FFmpeg DLL (Release x64)
      run: |
        cd ffmpeg
        msbuild ffmpeg.sln /p:Configuration=Release /p:Platform=x64

    - name: Collect DLL + LIB + headers
      run: |
        mkdir %INSTALL_DIR%
        xcopy /Y /S ffmpeg\bin\x64\Release\*.dll %INSTALL_DIR%\
        xcopy /Y /S ffmpeg\lib\x64\Release\*.lib %INSTALL_DIR%\
        xcopy /Y /S ffmpeg\include %INSTALL_DIR%\include\

    - name: Create ZIP
      run: |
        Compress-Archive -Path %INSTALL_DIR%\* -DestinationPath ffmpeg-x264-dll.zip

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ffmpeg-x264-dll.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
